### ISSUE TITLE
how OpenAIClient work?

### ISSUE THREAD

**Issue by lazywking** [haritheja-e/robot-utility-models#4]
Couldn't see anywhere OpenAIClient be called? how does OpenAIClient work in the project?

**Comment by haritheja-e** [comment]
Hi! Thank you for your interest in our work! We didn’t include code for running with GPT auto-retrying in our release as we hadn’t made it compatible with the UI (we tried to keep the UI minimal for easy use), and it requires command line use. I just pushed this code to a new branch [`gpt_retry`](https://github.com/haritheja-e/robot-utility-models/tree/gpt_retry) if you’d like to check it out. It’s called through the `_query_gpt` function which is called [here](https://github.com/haritheja-e/robot-utility-models/blob/f6d4e6efc9b1ef2894209e810e09a138b10a84cc/imitation-in-homes/robot/controller.py#L174), and can be run in command line by entering the instruction [`e + ↵`](https://github.com/haritheja-e/robot-utility-models/blob/f6d4e6efc9b1ef2894209e810e09a138b10a84cc/imitation-in-homes/robot/controller.py#L387) when prompted after running `run.py`. 

How it works: 
1. At the end of a fixed time interval, we send in every other image captured in the run into GPT-4o (either from wrist camera or head camera on our Hello Robot Stretch depending on task) and prompt it, again based on task. The response from GPT indicates task success/failure. All prompts can be found [here](https://github.com/haritheja-e/robot-utility-models/blob/f6d4e6efc9b1ef2894209e810e09a138b10a84cc/imitation-in-homes/robot/openai_client.py#L9). 
2. It retires from a new initial position if GPT-4o classifies the run as a failure. 

If you’d be interested in having this code compatible with the UI, let us know. Thanks!
